
/**
 * HARDCODED UI & FUNCTION REGISTRY
 * SINGLE SOURCE OF TRUTH
 * 
 * Rules:
 * 1. Every interactive element MUST have an ID here.
 * 2. Every logic flow MUST have a Function ID here.
 * 3. Mismatches cause System Halt.
 */

export const UI_REGISTRY = {
    // SIDEBAR NAVIGATION
    SIDEBAR_BTN_DASHBOARD: 'UI_SIDEBAR_BTN_DASHBOARD',
    SIDEBAR_BTN_NOTES: 'UI_SIDEBAR_BTN_NOTES',
    SIDEBAR_BTN_CHAT: 'UI_SIDEBAR_BTN_CHAT',
    SIDEBAR_BTN_TOOLS: 'UI_SIDEBAR_BTN_TOOLS',
    SIDEBAR_BTN_SYSTEM: 'UI_SIDEBAR_BTN_SYSTEM',
    SIDEBAR_BTN_SETTINGS: 'UI_SIDEBAR_BTN_SETTINGS',
    SIDEBAR_BTN_LOGO: 'UI_SIDEBAR_BTN_LOGO',

    // DASHBOARD
    DASHBOARD_BTN_SYSTEM_STATUS: 'UI_DASHBOARD_BTN_SYSTEM_STATUS',
    DASHBOARD_CARD_NOTES: 'UI_DASHBOARD_CARD_NOTES',
    DASHBOARD_CARD_SYNC: 'UI_DASHBOARD_CARD_SYNC',
    DASHBOARD_BENTO_CHAT: 'UI_DASHBOARD_BENTO_CHAT',
    DASHBOARD_BENTO_ARCHIVE: 'UI_DASHBOARD_BENTO_ARCHIVE',
    DASHBOARD_BENTO_TOOLS: 'UI_DASHBOARD_BENTO_TOOLS',
    DASHBOARD_BTN_RECENT_LOGS: 'UI_DASHBOARD_BTN_RECENT_LOGS',
    DASHBOARD_BTN_VAULT_TOGGLE: 'UI_DASHBOARD_BTN_VAULT_TOGGLE',

    // CHAT MODULE
    CHAT_BTN_MODEL_PICKER: 'UI_CHAT_BTN_MODEL_PICKER',
    CHAT_BTN_HISTORY: 'UI_CHAT_BTN_HISTORY',
    CHAT_BTN_LIVE_TOGGLE: 'UI_CHAT_BTN_LIVE_TOGGLE',
    CHAT_BTN_SCROLL_DOWN: 'UI_CHAT_BTN_SCROLL_DOWN',
    CHAT_INPUT_SEND: 'UI_CHAT_INPUT_SEND',
    CHAT_INPUT_ATTACH: 'UI_CHAT_INPUT_ATTACH',
    CHAT_INPUT_MIC: 'UI_CHAT_INPUT_MIC',
    CHAT_INPUT_NEW: 'UI_CHAT_INPUT_NEW',
    CHAT_SUGGESTION_CARD: 'UI_CHAT_SUGGESTION_CARD',

    // NOTES MODULE
    NOTES_BTN_CREATE: 'UI_NOTES_BTN_CREATE',
    NOTES_INPUT_SEARCH: 'UI_NOTES_INPUT_SEARCH',
    NOTES_BTN_FILTER_ARCHIVE: 'UI_NOTES_BTN_FILTER_ARCHIVE',
    NOTES_BTN_BATCH_MODE: 'UI_NOTES_BTN_BATCH_MODE',
    NOTES_CARD_ITEM: 'UI_NOTES_CARD_ITEM',
    NOTES_BTN_DELETE_ITEM: 'UI_NOTES_BTN_DELETE_ITEM',
    
    // TOOLS MODULE
    TOOLS_BTN_TAB_GEN: 'UI_TOOLS_BTN_TAB_GEN',
    TOOLS_BTN_TAB_VIS: 'UI_TOOLS_BTN_TAB_VIS',
    TOOLS_GEN_BTN_IMAGE: 'UI_TOOLS_GEN_BTN_IMAGE',
    TOOLS_GEN_BTN_VIDEO: 'UI_TOOLS_GEN_BTN_VIDEO',
    TOOLS_VIS_BTN_UPLOAD: 'UI_TOOLS_VIS_BTN_UPLOAD',
    TOOLS_VIS_BTN_CAMERA: 'UI_TOOLS_VIS_BTN_CAMERA',
    TOOLS_VIS_BTN_EDIT: 'UI_TOOLS_VIS_BTN_EDIT',

    // MECHANIC MODULE
    MECH_BTN_SCAN: 'UI_MECH_BTN_SCAN',
    MECH_BTN_REFRESH_KEYS: 'UI_MECH_BTN_REFRESH_KEYS',
    MECH_BTN_OPTIMIZE: 'UI_MECH_BTN_OPTIMIZE',
    MECH_BTN_CLEAR_LOGS: 'UI_MECH_BTN_CLEAR_LOGS',
    MECH_BTN_HARD_RESET: 'UI_MECH_BTN_HARD_RESET',
    MECH_INPUT_CLI: 'UI_MECH_INPUT_CLI',

    // SETTINGS
    SETTINGS_BTN_LANG_ID: 'UI_SETTINGS_BTN_LANG_ID',
    SETTINGS_BTN_LANG_EN: 'UI_SETTINGS_BTN_LANG_EN',
    SETTINGS_BTN_LANG_BN: 'UI_SETTINGS_BTN_LANG_BN',
    SETTINGS_BTN_THEME_SYSTEM: 'UI_SETTINGS_BTN_THEME_SYSTEM',
    SETTINGS_BTN_THEME_LIGHT: 'UI_SETTINGS_BTN_THEME_LIGHT',
    SETTINGS_BTN_THEME_DARK: 'UI_SETTINGS_BTN_THEME_DARK',
    SETTINGS_BTN_SAVE: 'UI_SETTINGS_BTN_SAVE',
    SETTINGS_BTN_RESET: 'UI_SETTINGS_BTN_RESET',
    SETTINGS_BTN_BACKUP: 'UI_SETTINGS_BTN_BACKUP',
    SETTINGS_BTN_RESTORE: 'UI_SETTINGS_BTN_RESTORE',
    
    // DEBUG
    DEBUG_TOGGLE: 'UI_DEBUG_TOGGLE'
} as const;

export const FN_REGISTRY = {
    // NAVIGATION
    NAVIGATE_TO_FEATURE: 'FN_NAVIGATE_TO_FEATURE',
    
    // DASHBOARD ACTIONS
    OPEN_SYSTEM_MECHANIC: 'FN_OPEN_SYSTEM_MECHANIC',
    TOGGLE_VAULT_LOCK: 'FN_TOGGLE_VAULT_LOCK',
    
    // CHAT ACTIONS
    CHAT_SEND_MESSAGE: 'FN_CHAT_SEND_MESSAGE',
    CHAT_NEW_SESSION: 'FN_CHAT_NEW_SESSION',
    CHAT_TOGGLE_LIVE: 'FN_CHAT_TOGGLE_LIVE',
    CHAT_LOAD_HISTORY: 'FN_CHAT_LOAD_HISTORY',
    CHAT_SELECT_MODEL: 'FN_CHAT_SELECT_MODEL',
    
    // NOTES ACTIONS
    NOTE_CREATE: 'FN_NOTE_CREATE',
    NOTE_DELETE: 'FN_NOTE_DELETE',
    NOTE_UPDATE: 'FN_NOTE_UPDATE',
    NOTE_SEARCH: 'FN_NOTE_SEARCH',
    NOTE_BATCH_ACTION: 'FN_NOTE_BATCH_ACTION',

    // TOOLS ACTIONS
    TOOL_GENERATE_IMAGE: 'FN_TOOL_GENERATE_IMAGE',
    TOOL_GENERATE_VIDEO: 'FN_TOOL_GENERATE_VIDEO',
    TOOL_ANALYZE_IMAGE: 'FN_TOOL_ANALYZE_IMAGE',
    TOOL_CAMERA_CAPTURE: 'FN_TOOL_CAMERA_CAPTURE',

    // MECHANIC ACTIONS
    MECH_RUN_DIAGNOSIS: 'FN_MECH_RUN_DIAGNOSIS',
    MECH_EXECUTE_FIX: 'FN_MECH_EXECUTE_FIX',
    MECH_CLI_EXEC: 'FN_MECH_CLI_EXEC',

    // SETTINGS ACTIONS
    SET_LANGUAGE: 'FN_SET_LANGUAGE',
    SET_THEME_MODE: 'FN_SET_THEME_MODE',
    SET_ACCENT_COLOR: 'FN_SET_ACCENT_COLOR',
    SAVE_CONFIG: 'FN_SAVE_CONFIG',
    RESET_SYSTEM: 'FN_RESET_SYSTEM',
    BACKUP_DATA: 'FN_BACKUP_DATA',
    RESTORE_DATA: 'FN_RESTORE_DATA',
    
    // SYSTEM
    TRIGGER_DEBUG: 'FN_TRIGGER_DEBUG',
    VALIDATE_REGISTRY: 'FN_VALIDATE_REGISTRY'
} as const;

// Type definitions for type safety enforcement
export type UI_ID = typeof UI_REGISTRY[keyof typeof UI_REGISTRY];
export type FN_ID = typeof FN_REGISTRY[keyof typeof FN_REGISTRY];
